name: NuCat Build

on:
  push:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Nucat
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Build Setup
      shell: bash
      run: mkdir bundle && makensis ./Install.nsi
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
          name: NuCat_Windows_Setup
          path: bundle/NuCat_Setup.exe
