name: NuCat Release

on:
  push:
    tags:
      - '*.*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Nucat
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Build Setup
      shell: bash
      run: mkdir bundle && makensis ./Install.nsi
    - name: Upload Windows Asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: NuCat_Windows/NuCat.zip
          asset_name: NuCat_Windows${{ github.ref_name }}.zip
          asset_content_type: application/zip
