name: NuCat Release

on:
  push:
    tags:
      - '*.*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build NuCat
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Copy Resource
      run: copy ./Other/Resource/* ./out/pack
    - name: Copy NuCat
      run: copy ./build/NuCat/Release/NuCat.exe ./out/pack
    - name: Build Setup
      shell: bash
      run: mkdir bundle && makensis ./Install.nsi
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
          tag_name: ${{ github.ref }}
          release_name: NuCat ${{ github.ref }}
          body_path: releasenote.md
          draft: true
          prerelease: false
          
    - name: Upload Windows Asset
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bundle/NuCat_Setup.exe
          asset_name: NuCat_Windows_Setup_${{ github.ref_name }}.exe
          asset_content_type: application/vnd.microsoft.portable-executable
